default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
  host: localhost

development:
  <<: *default
  database: garage_development

test:
  <<: *default
  database: garage_test
